# Site settings
title: Kauer Novels
description: A blog about lorem ipsum dolor sit amet
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Giovane Kauer
user_description: Kauer Novels
email: gfkauer@gmail.com
twitter_username: gfkauer
#github_username:  lorem_ipsum
#gplus_username:  lorem_ipsum
#disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Novel
    url: /novel
#  - title: About Me
#    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
